# TinyML - Support Vector Machine (Classifier)

In [56]:
#!pip install micromlgen

## 1. Importing libraries

In [57]:
from micromlgen import port
import pandas as pd
import plotly.graph_objects as go
import numpy as np
import plotly.express as px

from sklearn.svm import SVC
from sklearn.calibration import LabelEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import metrics

## 2. Load Dataset

The Iris dataset is a classic dataset in the field of machine learning and statistics. It was introduced by Sir Ronald A. Fisher in 1936 as an example of discriminant analysis. The dataset is often used for educational purposes and is a common starting point for the practice of pattern classification.


Attributes:

- Sepal length (in centimeters)

- Sepal width (in centimeters)

- Petal length (in centimeters)


Species:

- 0 - Setosa

- 1 - Versicolor

In [58]:
# Load iris dataset
data = load_iris()

# Create a DataFrame
df_iris = pd.DataFrame(data.data, columns=data.feature_names)


# Add target variable to the DataFrame
df_iris['target'] = data.target

# Remove NaN values
df = df_iris.dropna(axis='rows') #remove NaN

# Display the DataFrame
print(df_iris.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [59]:
df=df_iris.iloc[:100,1:4]

In [60]:
X=df.to_numpy()

# Converting string value to int type for labels: Setosa = 0, Versicolor = 1
y=df_iris.iloc[:100,-1]
y = LabelEncoder().fit_transform(y)

In [61]:
print(df.head())

   sepal width (cm)  petal length (cm)  petal width (cm)
0               3.5                1.4               0.2
1               3.0                1.4               0.2
2               3.2                1.3               0.2
3               3.1                1.5               0.2
4               3.6                1.4               0.2


## 3. Dataset Visualization 

In [62]:
fig = go.Figure()


fig.add_trace(go.Scatter3d(x=df['sepal width (cm)'], y= df['petal length (cm)'], z=df['petal width (cm)'], mode='markers', marker=dict(color='blue')))

fig.update_layout(scene=dict(xaxis_title='Sepal Length (cm)', yaxis_title='Sepal Width (cm)', zaxis_title='Petal Width (cm)'),
                  scene_camera=dict(eye=dict(x=1.87, y=0.88, z=-0.64)),
                  width=1000, height=600)
fig.show()

In [63]:
print('Input shape: ', X.shape)
print('Target variable shape: ', y.shape)

Input shape:  (100, 3)
Target variable shape:  (100,)


## 4. Split into training and test data

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [65]:
y_train


array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0], dtype=int64)

In [66]:
n = 7
print(y[n])
print(X[n])

0
[3.4 1.5 0.2]


In [67]:
X_train

array([[2.2, 4.5, 1.5],
       [3.6, 1.4, 0.2],
       [2.9, 1.4, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.6, 0.2],
       [2.8, 4.7, 1.2],
       [3.5, 1.3, 0.2],
       [2.9, 4.6, 1.3],
       [2.9, 4.2, 1.3],
       [3.2, 4.8, 1.8],
       [3.2, 1.6, 0.2],
       [3.8, 1.5, 0.3],
       [4.2, 1.4, 0.2],
       [3.5, 1.6, 0.6],
       [3.8, 1.7, 0.3],
       [3. , 4.4, 1.4],
       [2.6, 3.5, 1. ],
       [2.3, 4. , 1.3],
       [3. , 1.4, 0.3],
       [2.8, 4. , 1.3],
       [3.1, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 4.2, 1.5],
       [2.7, 5.1, 1.6],
       [2.7, 4.2, 1.3],
       [3. , 5. , 1.7],
       [3.3, 4.7, 1.6],
       [3.6, 1. , 0.2],
       [3.6, 1.4, 0.1],
       [3. , 4.2, 1.2],
       [3.4, 1.7, 0.2],
       [2.7, 3.9, 1.4],
       [2.3, 4.4, 1.3],
       [2.8, 4.1, 1.3],
       [3. , 1.4, 0.2],
       [3.4, 1.5, 0.2],
       [2.6, 4.4, 1.2],
       [3. , 4.6, 1.4],
       [2.8, 4.8, 1.4],
       [3.1, 4.4, 1.4],
       [3. , 4.5, 1.5],
       [3.9, 1.7

## 5. Create the classification model

In [68]:
model = SVC(gamma=0.0000001, kernel='linear')

## 6. Train the model

In [69]:
model.fit(X_train, y_train)

SVC(gamma=1e-07, kernel='linear')

## 6. Evaluating the model with the training data

In [70]:
training_predict = model.predict(X_train)

In [71]:
print(metrics.classification_report(y_train, training_predict, digits = 3))

              precision    recall  f1-score   support

           0      1.000     1.000     1.000        36
           1      1.000     1.000     1.000        39

    accuracy                          1.000        75
   macro avg      1.000     1.000     1.000        75
weighted avg      1.000     1.000     1.000        75



In [72]:
print(metrics.confusion_matrix(y_train, training_predict))

[[36  0]
 [ 0 39]]


In [73]:
print(f'Model accuracy: {round(metrics.accuracy_score(y_train, training_predict)*100,2)}%')

Model accuracy: 100.0%


## 7. Hyperlane Train Data Visualization 

In [74]:
x_grid, y_grid = np.meshgrid(np.linspace(X_train[:, 0].min(), X_train[:, 0].max(), 100),
                             np.linspace(X_train[:, 1].min(), X_train[:, 1].max(), 100))
z_grid = np.zeros_like(x_grid)


for i in range(len(x_grid)):
    for j in range(len(y_grid)):
        z_grid[i, j] = model.decision_function([[x_grid[i, j], y_grid[i, j], 0]])



fig = go.Figure()

fig.add_trace(go.Scatter3d(x=X_train[:, 0], y=X_train[:, 1], z=X_train[:, 2], mode='markers',
                           marker=dict(size=5, color=y_train, opacity=0.7), name='Dados de Treinamento'))

fig.add_trace(go.Surface(z=z_grid, x=x_grid, y=y_grid, opacity=0.5, colorscale='Bluered_r'))


fig.update_layout(scene=dict(xaxis_title='Sepal Width (cm)',
                             yaxis_title='Petal Length (cm)',
                             zaxis_title='Petal Width (cm)'))

fig.update_layout(width=1000, height=600)

fig.show()

## 8. Evaluating the model with test data

In [75]:
test_predict = model.predict(X_test)

In [76]:
test_predict

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1], dtype=int64)

In [77]:
X_test

array([[3.9, 1.3, 0.4],
       [3.4, 1.4, 0.2],
       [4.4, 1.5, 0.4],
       [4. , 1.2, 0.2],
       [3.2, 1.4, 0.2],
       [3.2, 4.5, 1.5],
       [2.9, 4.3, 1.3],
       [3.5, 1.4, 0.3],
       [3. , 4.5, 1.5],
       [4.1, 1.5, 0.1],
       [3.5, 1.5, 0.2],
       [3. , 4.1, 1.3],
       [3.5, 1.4, 0.2],
       [3.4, 1.5, 0.4],
       [2.3, 1.3, 0.3],
       [3.4, 4.5, 1.6],
       [2.5, 3. , 1.1],
       [3.4, 1.4, 0.3],
       [2.5, 4. , 1.3],
       [3.1, 4.7, 1.5],
       [3.2, 1.2, 0.2],
       [3.2, 4.7, 1.4],
       [2.5, 3.9, 1.1],
       [3.2, 1.3, 0.2],
       [2.8, 4.5, 1.3]])

In [78]:
print(metrics.classification_report(y_test, test_predict, digits = 3))

              precision    recall  f1-score   support

           0      1.000     1.000     1.000        14
           1      1.000     1.000     1.000        11

    accuracy                          1.000        25
   macro avg      1.000     1.000     1.000        25
weighted avg      1.000     1.000     1.000        25



In [79]:
print(metrics.confusion_matrix(y_test, test_predict))

[[14  0]
 [ 0 11]]


In [80]:
print(f'Model accuracy: {round(metrics.accuracy_score(y_test, test_predict)*100,2)}%')

Model accuracy: 100.0%


## 9. Hyperplane Test Data Visualization 

In [81]:
x_grid, y_grid = np.meshgrid(np.linspace(X_test[:, 0].min(), X_test[:, 0].max(), 100),
                             np.linspace(X_test[:, 1].min(), X_test[:, 1].max(), 100))
z_grid = np.zeros_like(x_grid)


for i in range(len(x_grid)):
    for j in range(len(y_grid)):
        z_grid[i, j] = model.decision_function([[x_grid[i, j], y_grid[i, j], 0]])


fig = go.Figure()


fig.add_trace(go.Scatter3d(x=X_test[:, 0], y=X_test[:, 1], z=X_test[:, 2], mode='markers',
                           marker=dict(size=5, color=y_test), name='Dados de Treinamento'))


fig.add_trace(go.Surface(z=z_grid, x=x_grid, y=y_grid, opacity=0.5, colorscale='Bluered_r'))

fig.update_layout(scene=dict(xaxis_title='Sepal Width (cm)',
                             yaxis_title='Petal Length (cm)',
                             zaxis_title='Petal Width (cm)'))

fig.update_layout(width=1000, height=600)

fig.show()

## 10. Obtaining the model to be implemented in the microcontroller

In [82]:
print(port(model))

#pragma once
#include <cstdarg>
namespace Eloquent {
    namespace ML {
        namespace Port {
            class SVM {
                public:
                    /**
                    * Predict class for features vector
                    */
                    int predict(float *x) {
                        float kernels[3] = { 0 };
                        float decisions[1] = { 0 };
                        int votes[2] = { 0 };
                        kernels[0] = compute_kernel(x,   3.4  , 1.9  , 0.2 );
                        kernels[1] = compute_kernel(x,   3.3  , 1.7  , 0.5 );
                        kernels[2] = compute_kernel(x,   2.4  , 3.3  , 1.0 );
                        float decision = -0.833910342285;
                        decision = decision - ( + kernels[0] * -0.31945543931  + kernels[1] * -0.240101867421 );
                        decision = decision - ( + kernels[2] * 0.559557306731 );

                        return decision > 0 ? 0 : 1;
                    

## 11. Saves the template in a .h file

In [83]:
with open('./SVMClassifier/SVMClassifier.h', 'w') as file:
    file.write(port(model))